version: '3'

services:
    mysql:
        container_name: wordpress-mysql
        image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    wordpress:
        container_name: wordpress
        image: wordpress:latest
        ports:
            - "${WORDPRESS_PORT}:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - db

volumes:
    db_data_wordpress: