version: '3'
volumes:
    data-web-base:
    data-bdd-base:

services:
    python:
        build: ./images/python
        volumes:
            - data-web:/home/siteweb
                  
    web:
        container_name: nginx
        image: nginx:alpine
        volumes:
            - data-web:/var/www/html
            - "./conf/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
           - "${NGINX_PORT}:80"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysql

    php:
        container_name: php-fpm
        image: nanoninja/php-fpm:${PHP_VERSION}
        container_name: php
        restart: always
        volumes:
            - data-web:/var/www/html

    mysql:
        container_name: mysql
        image: mysql:${MYSQL_VERSION}
        restart: always
        volumes: 
            - data-bdd:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '${PMA_PORT}:80'
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: always
        depends_on:
            - mysql 

    