version: "3"
volumes:
    git-data:
    git-config:

services:
    prometheus:
        container_name: prometheus
        image: prom/prometheus:v2.16.0
        ports:
            - "${PROMETHEUS_PORT}:9090"
    
    gitlab:
        container_name: gitlab
        image: gitlab/gitlab-ce
        restart: always
        volumes:
            - git-data:/var/opt/gitlab
            - git-config:/etc/gitlab
        ports:
            - "${GITLAB_HTTP_PORT}:80"
            - "${GITLAB_HTTPS_PORT}:443"
            - "${GITLAB_SSH_PORT}:22"
    
    #dns:
    #    container_name: dns
    #    build: ./images/bind9
    #    restart: always
    #    volumes:
    #        -
        